services:
  frontend:
    image: catsheue/links-frontend:latest
    ports:
      - "127.0.0.1:3004:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M